---
version: "3"

services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - /data/configs/wireguard/wg_confs/wg0.conf:/gluetun/wireguard/wg0.conf
    environment:
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
    ports:
      - 6881:6881/udp # qbittorrent
      - 8081:8081 # qbittorrent
      - 9117:9117 # Prowlarr
      - 9696:9696 # prowlarr
      - 8191:8191 # flaresolverr
      - 6881:6881 # qbittorrent
      - 7878:7878 # Radarr
      - 8787:8787 # Readarr
      - 8989:8989 # Sonarr
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:gluetun
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    volumes:
      - /data/configs/prowlarr:/config
      - /data/media:/mnt/media
      - /data/media/Downloads:/mnt/downloads
    depends_on:
      - flaresolverr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    restart: unless-stopped

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: service:gluetun
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:gluetun
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    volumes:
      - /data/configs/qbittorrent:/config
      - /data/media/Downloads:/mnt/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8081
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:gluetun
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    volumes:
      - /data/configs/radarr:/config
      - /data/media:/mnt/media
      - /data/media/Downloads:/mnt/downloads
    depends_on:
      - prowlarr
      - qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    restart: unless-stopped

  readarr:
    image: lscr.io/linuxserver/readarr:develop
    container_name: readarr
    network_mode: service:gluetun
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    volumes:
      - /data/configs/readarr:/config
      - /data/books:/mnt/books
      - /data/media/Downloads:/mnt/downloads
    depends_on:
      - prowlarr
      - qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:gluetun
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    volumes:
      - /data/configs/sonarr:/config
      - /data/media:/mnt/media
      - /data/media/Downloads:/mnt/downloads
    depends_on:
      - prowlarr
      - qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    restart: unless-stopped

  kavita:
    image: jvmilazz0/kavita:latest
    container_name: kavita
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    volumes:
      - /data/books:/mnt/books
      - /data/configs/kavita:/kavita/config
    ports:
      - "5000:5000"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    restart: unless-stopped
