---
version: "3"

services:
  autoheal:
    image: willfarrell/autoheal:1.2.0
    container_name: autoheal
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
      - AUTOHEAL_INTERVAL=5
      - AUTOHEAL_START_PERIOD=30
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    restart: always

  vpn:
    image: thrnz/docker-wireguard-pia
    container_name: vpn
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    volumes:
      - /vpn/forwarded_port:/pia-shared/port.dat
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - LOC=[REDACTED]
      - USER=[REDACTED]
      - PASS=[REDACTED]
      - LOCAL_NETWORK=192.168.0.0/24
      - PORT_FORWARDING=1
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.default.disable_ipv6=1
      - net.ipv6.conf.all.disable_ipv6=1
      - net.ipv6.conf.lo.disable_ipv6=1
    ports:
      - 8090:80 # speedtest-vpn
      - 8082:8082 # qbittorrent
      - 9117:9117 # Prowlarr
      - 9696:9696 # prowlarr
      - 8191:8191 # flaresolverr
      - 7878:7878 # Radarr
      - 8989:8989 # Sonarr
      - 6767:6767 # Bazarr
    healthcheck:
      test: ["CMD", "curl", "ipconfig.io"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always

  speedtest-vpn:
    container_name: speedtest-vpn
    image: henrywhitaker3/speedtest-tracker
    network_mode: service:vpn
    volumes:
      - /config/speedtest-vpn:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - OOKLA_EULA_GDPR=true
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    depends_on:
      vpn:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "ipconfig.io"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always

  speedtest:
    container_name: speedtest
    image: henrywhitaker3/speedtest-tracker
    ports:
      - 8091:80
    volumes:
      - /config/speedtest:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - OOKLA_EULA_GDPR=true
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    healthcheck:
      test: "curl -I www.example.org 2>/dev/null | head -n 1 | cut -d$' ' -f2"
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always

  prowlarr:
    image: linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:vpn
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    volumes:
      - /tank/configs/arr-stack/prowlarr:/config
      - /tank/data/media:/mnt/media
      - /tank/data/media/downloads:/mnt/downloads
    depends_on:
      vpn:
        condition: service_started
      flaresolverr:
        condition: service_started
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    healthcheck:
      test: ["CMD", "curl", "ipconfig.io"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always

  flaresolverr:
    image: flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    network_mode: service:vpn
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    depends_on:
      vpn:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "ipconfig.io"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    network_mode: service:vpn
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    volumes:
      - /tank/configs/arr-stack/qbittorrent:/config
      - /tank/data/media/downloads:/mnt/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
      - WEBUI_PORT=8082
    depends_on:
      vpn:
        condition: service_started
    healthcheck:
      test: ["CMD", "curl", "ipconfig.io"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always

  radarr:
    image: linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:vpn
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    volumes:
      - /tank/configs/arr-stack/radarr:/config
      - /tank/data/media:/mnt/media
      - /tank/data/media/downloads:/mnt/downloads
    depends_on:
      vpn:
        condition: service_started
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    healthcheck:
      test: ["CMD", "curl", "ipconfig.io"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always

  sonarr:
    image: linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:vpn
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    volumes:
      - /tank/configs/arr-stack/sonarr:/config
      - /tank/data/media:/mnt/media
      - /tank/data/media/downloads:/mnt/downloads
    depends_on:
      vpn:
        condition: service_started
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    healthcheck:
      test: ["CMD", "curl", "ipconfig.io"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: bazarr
    network_mode: service:vpn
    logging:
      options:
        max-size: "5M"
        max-file: "3"
    volumes:
      - /tank/configs/arr-stack/bazarr:/config
      - /tank/data/media:/mnt/media
    depends_on:
      vpn:
        condition: service_started
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    healthcheck:
      test: ["CMD", "curl", "ipconfig.io"]
      interval: 60s
      timeout: 5s
      retries: 3
      start_period: 30s
      start_interval: 5s
    restart: always
