version: "3"
services:
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    ports:
      - "9091:9090"
    volumes:
      - "/tank/configs/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  grafana:
    container_name: grafana
    image: grafana/grafana:latest

    ports:
      - "3000:3000"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkata
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - DS_PROMETHEUS=prometheus
    volumes:
      - "/tank/configs/monitoring/grafana/data:/var/lib/grafana"
      - "/tank/configs/monitoring/grafana/datasources/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml"
      - "/tank/configs/monitoring/grafana/dashboards:/var/lib/grafana/dashboards"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
