global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "cadvisor"
    static_configs:
      - targets:
        - localhost:8100

  - job_name: "node-exporter"
    static_configs:
      - targets:
        - localhost:9100
        - 192.168.0.190:9100
        - 192.168.0.101:9100
        - 192.168.0.102:9100
        - 192.168.0.103:9100
        - 192.168.0.104:9100
        - 192.168.0.106:9100
        - 192.168.0.108:9100
        - 192.168.0.109:9100
        - 192.168.0.110:9100
        - 192.168.0.111:9100
