global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
        - 192.168.0.100:9091

  - job_name: "cadvisor"
    static_configs:
      - targets:
        - 192.168.0.100:8081

  - job_name: "node-exporter"
    static_configs:
      - targets:
        - 192.168.0.100:9100
