version: "3"
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Asia/Kolkat
      - SECRET_ENCRYPTION_KEY=685e63b1d8241e881e7ca4dd2f66dff344d425a76843c75138a39d96e3406e93
    volumes:
      - /tank/configs/homarr/appdata:/appdata
    ports:
      - "7575:7575"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
