version: "3"
services:
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    volumes:
      - /tank/configs/homarr/configs:/app/data/configs
      - /tank/configs/homarr/icons:/app/public/icons
      - /tank/configs/homarr/data:/data
    ports:
      - "7575:7575"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
