version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - "8096:8096"
    volumes:
      - /tank/configs/jellyfin/config:/config
      - /tank/configs/jellyfin/cache:/cache
      - /tank/data/media/movies:/movies
      - /tank/data/media/shows:/shows
      - /tank/data/media/events:/events
      - /tank/data/media/misc:/misc
    environment:
      - TZ=Asia/Kolkata
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    devices:
      - "/dev/dri/card0:/dev/dri/card0"
      - "/dev/dri/renderD128:/dev/dri/renderD128"
    privileged: true
    restart: "unless-stopped"
